config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#index"

  get 'welcome/index'

  get 'nomnichi', to: 'articles#index'
  post 'articles/preview', to: 'articles#preview'
  resources :articles, except: :show
  get 'articles/search'
  get 'articles/:perma_link', to: 'articles#show'
  get 'articles/archive/:param', to: 'articles#archive'
  resources :comments
  resources :articles
  get 'settings', to:  'users#edit'
  put 'users/:id/change_password', to: 'users#change_password'
  resources :users, except: :edit

  get "/auth/:provider/callback", to: "gate#omniauth"
  match "gate/login", :via => [:get, :post]
  get "gate/logout"
  get '*path', to: 'application#render_static_page'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  default_scope { order("created_at desc").visible }
  scope :visible, -> { User.login? ? Comment.all : Comment.approved }
  scope :approved, -> { joins(:article).where("approved = ?", true) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate, except: [:index, :show]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    @comment = Comment.new
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @article = @comment.article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to controller: :articles, action: :show, perma_link: @article.perma_link, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @article = @comment.article

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to controller: :articles, action: :show, perma_link: @article.perma_link, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    @article = @comment.article
    respond_to do |format|
      format.html { redirect_to controller: :articles, action: :show, perma_link: @article.perma_link, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:user_id, :body, :article_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% article = @article %>
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="comment">
  <div class="field">
    <%= f.hidden_field :user_id, value: User.current.id %><br>
  </div>
  <div class="field">
    <%= f.label :New_comment %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :article_id, value: article.id %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/comments/_list_comment.html.erb
<% article = @article %>
<% if @article.comments.length > 0 %>
<% @article.comments.each do |comment| %>
<div id="comment">
  <div>
  <%= comment.body %>
  </div>
  <div class="clear">
  </div>
  <div class="article-info">
    <span class="glyphicon glyphicon-user"></span>
    <%= comment.user.ident %>
    <span class="glyphicon glyphicon-time"></span>
    <%= comment.created_at %>
  <%= link_to '編集', edit_comment_path(comment) unless User.current.nil? %>
  <%= link_to '削除', comment_path(comment), method: 'DELETE' unless User.current.nil? %>
  </div>
  <div class="clear">
  </div>
  <hr>
</div>
<% end %>
<% else %>
<div>No comment</div>
<% end %>
<br>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>
<%= form_for(@comment) do |f| %>
<% if @comment.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="comment">
  <div class="field">
    <%= f.hidden_field :user_id, value: @comment.user_id %><br>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :article_id, value: @comment.article.id %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

<!-- <%= link_to 'Show', @comment %> | -->
<%= link_to 'Back', articles_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Body</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.article_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>