config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#index"

  get 'welcome/index'

  get 'nomnichi', to: 'articles#index'
  post 'articles/preview', to: 'articles#preview'
  resources :articles, except: :show
  get 'articles/search'
  get 'articles/:perma_link', to: 'articles#show'
  get 'articles/archive/:param', to: 'articles#archive'
  resources :comments
  resources :articles
  get 'settings', to:  'users#edit'
  put 'users/:id/change_password', to: 'users#change_password'
  resources :users, except: :edit

  get "/auth/:provider/callback", to: "gate#omniauth"
  match "gate/login", :via => [:get, :post]
  get "gate/logout"
  get '*path', to: 'application#render_static_page'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :user_id, presence: true
  validates :title, presence: true
  validates :perma_link, presence: true, uniqueness: true, unless: proc { [:except_preview].include?(validation_context) }
  validates :format, presence: true, inclusion: {in: ["Kramdown", "GFM"]}

  paginates_per 10

  default_scope { order("published_on desc") }
  scope :visible, -> { User.login? ? Article.all : Article.approved }
  scope :approved, -> { where("approved = ?", true) }
  scope :search, ->(query) {
    where("title LIKE ? or content LIKE ?", "%#{query}%", "%#{query}%")
  }

  def previous
    Article.where("published_on < ?", published_on).first
  end

  def next
    Article.where("published_on > ?", published_on).reorder("published_on asc").first
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate, except: [:index, :show, :archive, :search]
  before_action :set_article, only: [:edit, :update, :destroy]
  before_action :set_parameters_for_sidebar, only: [:index, :search]
  before_action :set_article_by_perma_link, only: [:show]
  before_action :call_auth_if_private_article, only: [:show]
  before_action :count_up, only: [:show]

  # GET /articles
  # GET /articles.json
  def index
    if User.current
      if params[:start] && params[:end]
        articles = Article.visible.where("created_at >= ? and created_at <= ?",
                                 DateTime.parse(params[:start]),
                                 DateTime.parse(params[:end]))
      else
        articles = Article.visible.all
      end
    else
      if params[:start] && params[:end]
        articles = Article.visible.where("approved = ? and created_at >= ? and created_at <= ?",
                                 true,
                                 DateTime.parse(params[:start]),
                                 DateTime.parse(params[:end]))
      else
        articles = Article.visible.where("approved = ?",true)
      end
    end
    @articles = articles.page(params[:page])

    respond_to do |format|
      format.html
      format.json
      format.rss { render layout: false }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = Comment.new
  end

  # GET /articles/new
  def new
    @article = Article.new
    @article.content = "<!-- folding -->"
    @article.perma_link = User.current.ident + "-" + Time.now.to_s(:perma_link)
    @article.user_id = User.current.id
    @article.published_on = Time.now
    @article.format = "GFM"
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to action: :show, perma_link: @article.perma_link, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to action: :show, perma_link: @article.perma_link, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    if Article.new(article_params).invalid?(:except_preview)
      render text: "Bad request", status: 400
    else
      title =
        """
        <div class='title-bar'>
          <span class='title'>
            #{article_params[:title]}
          </span>
        </div>
        """
      clear = "<div class='clear'></div>"

      render text: title + Kramdown::Document.new(article_params[:content],
                                                  input: article_params[:format],
                                                  syntax_highlighter: :rouge,
                                                  syntax_highlighter_opts: {css_class: 'highlight'}
                                                 ).to_html + clear
    end

  end

  def archive
    year = params[:param].split("-")[0].to_i
    month = params[:param].split("-")[1].to_i

    if month != 0
      start_time = DateTime.new(year, month, 1)
      end_time = (start_time >> 1) - Rational(1, 24 * 60 * 60)
    else
      start_time = DateTime.new(year, 4, 1)
      end_time = DateTime.new(year + 1, 3, 31, 23, 59, 59, 99)
    end

    respond_to do |format|
      format.html { redirect_to action: :index, start: start_time, end: end_time}
    end

  end

  def search
    articles = User.current ? Article.visible.all : Article.visible.approved
    articles = articles.search(params[:query]) if params[:query].present?
    @articles = articles.page(params[:page])
    respond_to do |format|
      format.html { render action: "index" }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  def call_auth_if_private_article
    if !@article.approved
      authenticate()
    end
  end

  def set_article_by_perma_link
    @article = Article.find_by!(perma_link: params[:perma_link])
  end

  def set_parameters_for_sidebar
    @article_all = Article.visible.all
    @comments = Comment.all.slice(0..4)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:user_id, :title, :perma_link, :content, :published_on, :approved, :count, :promote_headline, :format)
  end

  #count up the number of view
  def count_up
    @article.count = @article.count + 1
    @article.save
  end
end

app/helpers/articles_helper.rb
# coding: utf-8
module ArticlesHelper
  def fold_article(content)
    if /<!-- folding -->/ =~ content then
      Sanitize.clean($`)
    else
      Sanitize.clean(content.split(/\r?\n/)[0, 3].join)
    end
  end

  def list_headline(nth)
    Article.visible.where(promote_headline: true).order("published_on desc").slice(0..nth)
  end

  def link_to_article_by_perma_link(str, article, option = {})
    link_to str, {controller: :articles, action: :show, perma_link: article.perma_link}, option
  end

  def fold_comment(body)
    comment_size = 30
    if get_str_bytesize(body) > comment_size
      bytes, fold_pos = get_fold_position(body, comment_size)
      return body.slice(0..fold_pos) + " ..."
    else
      return body
    end
  end

  def list_year_archives(articles)
    return [] if articles.empty?
    year_archives = []
    newest_year = articles.first.created_at.year
    oldest_year = articles.last.created_at.year
    newest_year.downto(oldest_year - 1).each do |year|
      start_time = DateTime.new(year, 4, 1)
      end_time = DateTime.new(year + 1, 3, 31, 23, 59, 59, 99)
      item = articles.where("created_at >= ? and created_at <= ?", start_time, end_time)
      item = item.where("approved = ?", true) unless User.current
      year_archives << {:year => "#{start_time.year}", :item => item.length, :month => list_month_archives(item, start_time.year)} unless item.empty?
    end
    year_archives.select
  end

  def list_month_archives(articles, year)
    month_archives = []
    newest_month = articles.first.created_at.month
    oldest_month = articles.last.created_at.month
    ["04","05","06","07","08","09","10","11","12","01","02","03"].each do |month|
      item = articles.where("strftime('%m',created_at) = ?",month)
      item = item.where("approved = ?", true) unless User.current
      if ["01", "02", "03"].include?(month)
        month_archives << {:month => "#{month}", :item => item.length, :param => (year + 1).to_s + "-" + month}
      else
        month_archives << {:month => "#{month}", :item => item.length, :param => year.to_s + "-" + month}
      end
    end
    month_archives.select {|month| month[:item] != 0}
  end

  def tweet_button(title, author)
    str = "<a href='https://twitter.com/share' class='twitter-share-button' data-url='#{request.url}' data-text='#{title} by #{author}  - ノムニチ'></a>".html_safe
  end

  def alert_no_articles(articles)
    "<h1> no articles </h1>".html_safe if articles.length == 0
  end

  private

  def get_char_bytesize(c)
    c.bytesize == 1 ? 1 : 2
  end

  def get_str_bytesize(str)
    str.each_char.map {|char| get_char_bytesize(char)}.inject(:+)
  end

  def get_fold_position(str, length)
    bytes = 0
    str.chars.each_with_index do |c, i|
      bytes += get_char_bytesize(c)
      return bytes, i if bytes >= length
    end
  end
end

app/views/articles/_card.html.erb
<div class="box">
  <div class="<%= article.approved ? "title-header" : "private-title-header" %>" >
    <%= link_to_article_by_perma_link(article.title, article, {class: "title"}) %>
    <% unless article.approved %>
      <%= fa_icon "lock", class: "private title" %>
    <% end %>
  </div>
  <%= render partial: "articles/info", locals: {article: article} %>
  <div class="clear">
  </div>
  <div>
    <%= raw fold_article(article.content) %>
  </div>
  <hr>
  <%= link_to_article_by_perma_link("#{fa_icon 'play'} Read More".html_safe, article) %>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :format %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <%= f.hidden_field :perma_link %>

  <div class="field">
    <%= f.label :published_on %><br>
    <%= f.datetime_local_field :published_on, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :approved %>
    <%= f.check_box :approved %>
  </div>

  <div class="field">
    <%= f.label :promote_headline %>
    <%= f.check_box :promote_headline %>
  </div>

  <%= f.hidden_field :count %>

  <div id="photo_inserter">
    <span class="message"></span>
    &nbsp;
    <a class="share" href="#" title="Insert to Write pane">
      <i class="fa fa-fw fa-share-alt"></i>
    </a>
    &nbsp;
    <a class="remove" href="#" title="Clear all marks">
      <i class="fa fa-fw fa-remove"></i>
    </a>
  </div>


  <ul class="nav nav-tabs" role="tablist">
    <li class="active" role="presentation">
      <a aria-controls="write" data-toggle="tab" href="#write" id="write-tab" role="tab">Write</a>
    </li>
    <li role="presentation">
      <a aria-controls="preview" data-toggle="tab" href="#preview" id="preview-tab" role="tab">Preview</a>
    </li>
    <li role="presentation">
      <a aria-controls="photo" data-toggle="tab" href="#photo" id="photo-tab" role="tab">Photo</a>
    </li>
  </ul>

  <div class="field form-group">
    <div class="tab-content">
      <div class="tab-pane active" id="write" role="tabpanel">
	<%= f.text_area :content, class: "form-control", rows: 20, wrap: :off %>
      </div>
      <div class="tab-pane preview_area" id="preview" role="tabpanel">
      </div>
      <div class="tab-pane" id="photo" role="tabpanel">
        ここに埋める
      </div>
    </div>
  </div>

  <%= f.submit class: 'btn btn-default' %>
<% end %>

<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<!-- add ``blueimp-gallery-controls'' to class= if you need some control buttons -->
<div id="blueimp-gallery" class="blueimp-gallery" data-use-bootstrap-modal="false">
  <!-- The container for the modal slides -->
  <div class="slides"></div>
  <!-- Controls for the borderless lightbox -->
  <h3 class="title"></h3>
  <a class="checkmark"><i class="fa fa-check-circle"></i></a>
  <a class="prev">‹</a>
  <a class="next">›</a>
  <a class="close">×</a>
  <a class="play-pause"></a>
  <ol class="indicator"></ol>
  <!-- The modal dialog, which will be used to wrap the lightbox content -->
  <div class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" aria-hidden="true">&times;</button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body next"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default pull-left prev">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Previous
          </button>
          <button type="button" class="btn btn-primary next">
            Next
            <i class="glyphicon glyphicon-chevron-right"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/_info.html.erb
<div class="article-info">
  <%= glyphicon "eye-open" %>
  <%= article.count %>
  <%= glyphicon "user" %>
  <%= article.user.ident %>
  <%= glyphicon "time" %>
  <%= article.published_on.to_s(:date) %>
  <%= glyphicon "comment" %>
  <%= article.comments.length %>
</div>

app/views/articles/_side_bar.html.erb
<div class="side_bar">
  <%= form_tag articles_search_path, method: 'GET' do %>
    <div class="input-group" id="search-article">
      <%= text_field_tag :query, nil, class: "form-control", placeholder: "Search Articles" %>
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">
          <%= glyphicon "search" %>
        </button>
      </span>
    </div>
  <% end %>
  <h5 class="side-title">Comment</h5>
  <hr class="border">
  <% comments.each do |comment| %>
    <p class="comment-article-title"><%= link_to_article_by_perma_link(comment.article.title, comment.article) %></p>
    <p class="comment-body"> <%= fold_comment(comment.body) %></p>
    <p class="comment-name">by <%= comment.user.ident %></p>
  <% end %>
  <h5 class="side-title">Archives</h5>
  <hr class="border">
  <ul class="yearly">
    <% list_year_archives(articles).each do |year| %>
      <li><%= link_to "#{year[:year]}年度(#{year[:item]})", controller: "articles", action: "archive", param: year[:year]%>
        <ul>
          <% year[:month].each do |month| %>
            <li><%= link_to("#{month[:month]}月(#{month[:item]})", controller: "articles", action: "archive", param: month[:param]) %></li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/articles/edit.html.erb
<%= render 'form' %>
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-md-9 col-sm-8 text-center hidden-xs">
    <%= paginate @articles, window: 3 %>
  </div>
  <div class="col-xs-12 text-center visible-xs">
    <%= paginate @articles, window: 1 %>
  </div>
</div>
<div class="row row-offcanvas row-offcanvas-right">
  <div class="col-md-9 col-sm-8 articles">
    <%= alert_no_articles(@articles) %>
    <%= render partial: "card", collection: @articles, as: :article %>
  </div>
  <div class="col-md-3 col-sm-4 sidebar-offcanvas" id="offcanvas-side-bar">
    <%= render :partial => 'side_bar', :locals => {:articles => @article_all, :comments => @comments } %>
  </div>
  <div class="pull-right visible-xs" id="side-bar-open-button">
    <button class="btn btn-default btn-xs" data-toggle="offcanvas" data-target="#offcanvas-side-bar">
      <%= fa_icon "arrow-left" %> Side menu
    </button>
  </div>
</div>
<div class="row">
  <div class="col-md-9 col-sm-8 text-center hidden-xs">
    <%= paginate @articles, window: 3 %>
  </div>
  <div class="col-xs-12 text-center visible-xs">
    <%= paginate @articles, window: 1 %>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>

<p id="notice"><%= notice %></p>

<div class="col-md-9">
  <div class="row">
    <div class="box">
      <div class="title-bar">
        <span class="title">
          <%= @article.title %>
        </span>
      </div>
      <%= render partial: "info", locals: {article: @article} %>

      <div class="clear">
      </div>

      <div class="content">
        <%= raw Kramdown::Document.new(@article.content,
                                       input: @article.format,
                                       syntax_highlighter: :rouge,
                                       syntax_highlighter_opts: {css_class: 'highlight'}
                                       ).to_html %>
      </div>

      <div class="share-button">
	<%= tweet_button(@article.title, @article.user.ident) %>
      </div>

      <div class="clear">
      </div>

      <hr>

      <div class="row link-boxes">
        <% if p = @article.previous %>
          <%= link_to_article_by_perma_link(fa_icon("chevron-left", text: p.title),
                                            p,
                                            {class: "col-xs-6 link-box"}) %>
        <% end %>
        <% if n = @article.next %>
          <%= link_to_article_by_perma_link(fa_icon("chevron-right", text: n.title, right: true),
                                            n,
                                            {class: "col-xs-6 link-box"}) %>
        <% end %>
      </div>

      <hr>

      <%= link_to fa_icon("home"), articles_path %>

      <% unless User.current.nil? %>
        <div class="article-info">
          <%= link_to edit_article_path(@article) do %>
            <%= fa_icon "pencil" %>
          <% end %>
          <%= link_to article_path(@article), method: :delete, data: {confirm: 'Are you sure?'} do %>
            <%= fa_icon "trash" %>
          <% end %>
        </div>
      <% end %>

      <div class="clear">
      </div>

    </div>

    <div class="box">
      <div class="title-bar">
        <span class="title">
          Comment
        </span>
      </div>
      <hr>
      <%= render :partial => '/comments/list_comment',:locals => {:article => @article} %>
      <%= render :partial => '/comments/form',:locals => {:article => @article} unless User.current.nil?%>
    </div>

    <div class="clear">
    </div>
  </div>
</div>